#!/bin/dash
# Parse command line arguments
FORCE=false
CACHED=false
FILES=""

while [ $# -gt 0 ]; do
    case $1 in
        --force)
            FORCE=true
            ;;
        --cached)
            CACHED=true
            ;;
        *)
            FILES="$FILES $1"
            ;;
    esac
    shift
done

# Check if any files were provided
if [ -z "$FILES" ]; then
    echo "$0: error: No files specified"
    exit 1
fi

# Check if .pushy directory exists
PUSHY_DIR=".pushy"
INDEX_DIR="$PUSHY_DIR/index"
commit_number=$(cat "$PUSHY_DIR/commit_number")
commit_number=$((commit_number-1))
COMMIT_DIR="$PUSHY_DIR/commits/commit$commit_number"
if [ ! -d "$PUSHY_DIR" ]; then
    echo "$0: error: pushy repository directory .pushy not found"
    exit 1
fi

for FILE in $FILES; do
    # Check if the file exists in the index
    if [ -f "$INDEX_DIR/$FILE" ]; then

        # Check if --cached option is specified
        if [ "$CACHED" = true ]; then
            if [ "$FORCE" != true ] && [ -f "$COMMIT_DIR/$FILE" ] && ! diff "$INDEX_DIR/$FILE" "$COMMIT_DIR/$FILE" >/dev/null && ! diff "$INDEX_DIR/$FILE" "$FILE" >/dev/null; then   
                echo "$0: error: '$FILE' in index is different to both the working file and the repository"
                exit 1
            fi
            rm "$INDEX_DIR/$FILE"
        else
            # Check if the file exists in the current directory
            if [ -f "$FILE" ]; then
                # Check if --force option is specified
                if [ "$FORCE" = true ]; then
                    rm "$FILE"
                else
                    if [ ! -f "$COMMIT_DIR/$FILE" ]; then
                        echo "$0: error: '$FILE' has staged changes in the index"
                        exit 1
                    fi
                    if ! diff "$INDEX_DIR/$FILE" "$FILE" >/dev/null; then 
                        if ! diff "$INDEX_DIR/$FILE" "$COMMIT_DIR/$FILE" >/dev/null; then
                            echo "$0: error: '$FILE' in index is different to both the working file and the repository"
                        else
                            echo "$0: error: '$FILE' in the repository is different to the working file"
                        fi
                        exit 1
                    else
                        if ! diff "$INDEX_DIR/$FILE" "$COMMIT_DIR/$FILE" >/dev/null && ! diff "$FILE" "$COMMIT_DIR/$FILE" >/dev/null; then
                            echo "$0: error: '$FILE' has staged changes in the index"
                            exit 1
                        fi
                    fi
                    

                    rm "$FILE"
                fi
            else
                
                echo "Error: $FILE not found in the current directory."
            fi
            # Remove the file from the index
            rm "$INDEX_DIR/$FILE"
        fi
    else
        echo "$0: error: '$FILE' is not in the pushy repository"
    fi
done
